### ISSUE TITLE
Ultralight.dll is missing, but I linked statically

### ISSUE THREAD

**Issue by Commanderguy** [ultralight-ux/Ultralight#144]
Everytime I try to create a window, I get an error saying that I forgot to include Ultralight.dll, but I linked the files statically with Ultralight.lib

**Comment by adamjs** [comment]
That DLL (along with WebCore.dll and UltralighCore.dll) is/are still required-- Ultralight.lib is considered an import library and only contains symbol declarations for code contained within the DLL. 

I don't offer static linkage partly because WebCore contains LGPL code (if you link to it statically it forces you to distribute your project as LGPL as well).
