### ISSUE TITLE
Does Ultralight use the v8 Engine?

### ISSUE THREAD

**Issue by dexter4life** [ultralight-ux/Ultralight#181]
I am new to this ultralight, and although having used nwjs and electronjs. What is the JavaScript engine for Ultralight based on? And can I use the node.dll with Ultralight

**Comment by maierfelix** [comment]
Ultralight uses the js engine of webkit, called [JavaScriptCore](https://trac.webkit.org/wiki/JavaScriptCore). Bindings to node.js are [planned](https://github.com/ultralight-ux/Ultralight/issues/21), though I'm not sure if intergrating node.js (instead of JavaScriptCore) is on the road map as well @adamjs

**Comment by dexter4life** [comment]
But can this JavaScriptCore run webgl completely supporting all the features presented in webgl?

**Comment by adamjs** [comment]
WebGL is currently not supported but is planned-- please see this thread for missing renderer features: https://github.com/ultralight-ux/Ultralight/issues/178
