### ISSUE TITLE
Is it possible to launch the program without console window?

### ISSUE THREAD

**Issue by TheGreyRaven** [ultralight-ux/Ultralight#222]
Hi!
I recently found Ultralight and I think it is great so far, I have been working on a small application for me and my friends, one thing that annoys me is the console window that spawns when starting the program.

I tried changing the SubSystem in the Linker settings but that did not help and gives me a Link error.
Is it possible to get rid of the console window or am I stuck with it?

**Comment by Dan4x8** [comment]
I'm assuming you're talking about a cpp project and that you want to use Ultralight in a classic win UI. Changing the Subsystem is your first step there, but you might want to be also aware, that you need to get rid of `int main()` and use `int WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR lpCmdLine, INT nCmdShow)` instead.

It might also help if you could describe the linker error a bit more; but I can tell from experience that it is possible to get rid of the console window and it's about a c/cpp thingie and not Ultralight itself.

**Comment by TheGreyRaven** [comment]
I tried that too earlier, I started with an Empty Project from the Visual Studio and changed the subsystem, the link error is the following:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	App	C:\Users\Raven\source\repos\Loader\Debug\App.exe	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _wWinMain@16 referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)	App	C:\Users\Raven\source\repos\App\App\LIBCMT.lib(exe_wwinmain.obj)	1	

```

**Comment by Dan4x8** [comment]
Awk. I hate linker errors. You probably can't imagine how many hours I already lost thanks to them. Unfortunately I don't have a copy of the source anymore where I did it with success (not on the project anymore) but I'll doublecheck when I'm home. You might wanna doublecheck meanwhile the linked libs/files especially considering x86 vs x64 libs and if it matches your compile settings. 
But since it sounds your starting out you might want to create a new win project instead of an empty one - so VS should take care of the linked files.

**Comment by TheGreyRaven** [comment]
@Dan4x8 I managed to get it working after creating a new project using the Windows Desktop Wizard, anyhow thank you for the help!
