### ISSUE TITLE
Very unsharp Font. ClearType?

### ISSUE THREAD

**Issue by Gurkengewuerz** [ultralight-ux/Ultralight#251]
When i test Ultralight, my fonts are very unsharp. The example image shows on the left side chrome with a very sharp font and on the right side Ultralight. Is this somehow ClearType related? Is the currently any workaround? 

![2020-05-17_03-00-14](https://user-images.githubusercontent.com/10966337/82133300-db8fd780-97ea-11ea-84f9-4e7096635819.png)

Seems to be #194 related?

**Comment by Gurkengewuerz** [comment]
Seems like #124 is realted. @0x416c69 have you any updates?

**Comment by Gurkengewuerz** [comment]
Seems like #124 is realted. @0x416c69 have you any updates? @adamjs closed your issue but the issue is still present :/

**Comment by adamjs** [comment]
Hey there, this issue is resolved in the 1.2 branch as part of a major rehaul of the compositor-- this has improved pixel-snapping logic for all geometry (text glyphs, borders, rects, etc.), especially when fractional device scales are used.

I'll be commiting the updated modules to the master Ultralight repo this coming week and will update this thread when I do.

**Comment by Gurkengewuerz** [comment]
Thanks. This would be great! 🥰

**Comment by adamjs** [comment]
This should be fixed in trunk.
