### ISSUE TITLE
Please update ultralight-sdk-latest-win-x86.7z

### ISSUE THREAD

**Issue by shithappens2016** [ultralight-ux/Ultralight#308]
It is out of date.

**Comment by adamjs** [comment]
We no longer support x86 (32-bit) natively in the 1.2 branch.

WebKit (specifically JavaScriptCore) dropped x86 support more than a year
ago and we had to follow suit when we merged latest changes from upstream.
(This is a hard requirement, some core structures in JavaScriptCore now
require 64-bit addresses)

The only other alternative is to host the 64-bit DLL in an external process
and use inter-process communication to shuttle the rendered pixels back to
a 32-bit host application.

I’m working on a multi-process layer on top of the Ultralight API for
process isolation that will allow this but may take a while to ship. I’m
updating the roadmap tomorrow.

On Oct 29, 2020, at 12:54 AM, shithappens2016 <notifications@github.com>
wrote:

﻿

It is out of date.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ultralight-ux/Ultralight/issues/308>, or unsubscribe
