### ISSUE TITLE
ultralight::FileHandle is not a consistent size across platforms

### ISSUE THREAD

**Issue by GenuineAster** [ultralight-ux/Ultralight#343]
On Windows, `FileHandle` is typedef'd to `size_t`, which is 64-bits on all platforms supported by Ultralight, but on Linux it's typedef'd to `int`, which is 32-bits on all platforms supported by Ultralight. It would be really nice if this was consistent across platforms so we don't end up with differing code on each platform (or an insane amount of `static_cast`s) just to deal with the different file handle type.

In my opinion, it's nicer to have handles be at least pointer-sized so we can fit an actual pointer to an internal file object into the handle, so I'd rather it just be `size_t` on all platforms.

**Comment by adamjs** [comment]
The motivation for using an `int` on non-Windows platforms is because this matches the file handle type used in the native POSIX APIs (macOS/Linux). 

I agree that it would be more portable to use a `size_t` across all instead of making special considerations for POSIX  (especially WRT storing pointers or other custom file handle types). I'll make the change.

**Comment by adamjs** [comment]
Task complete, available in latest trunk.
