### ISSUE TITLE
Browser demo won't run 'api-ms-win-shcore-scaling-l1-1-1.dll is missing'

### ISSUE THREAD

**Issue by warrickb** [ultralight-ux/ultralight#50]
Building from the VS solution, then running the browser demo gives the error 'api-ms-win-shcore-scaling-l1-1-1.dll is missing'.

sdk 0.9.1
VS2017 15.8.7
Win7 64bit latest updates

**Comment by NegativeIQ** [comment]
Same here, Windows 7 x64 SP1

**Comment by manuel76413** [comment]
Same here, Windows 7 x64 SP1

**Comment by dasoe** [comment]
Same here, Windows 7 x64 SP1
VS2017 15.5.1
ultralight 1.0 release

**Comment by adamjs** [comment]
It’s because Shcore (used for GetDPIForMonitor in AppCore.dll) is only
available in Windows 8.1 and above.

We should do runtime detection of the Windows version and load the DLL
dynamically (and fall back to system-wide DPI in older Windows versions).

I’ll make the changes.

On Mar 21, 2019, at 12:42 AM, dasoe <notifications@github.com> wrote:

Same here, Windows 7 x64 SP1
VS2017 15.5.1
ultralight 1.0 release

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ultralight-ux/ultralight/issues/50#issuecomment-475136248>,
or mute the thread

**Comment by adamjs** [comment]
Just added a fix for this issue in the dev branch-- https://github.com/ultralight-ux/ultralight/commit/011e150473c868908b4eded00bc33d74432c4644

Welcome to try out those binaries now, I'll test tomorrow once my Win7 VM is set up.

**Comment by dasoe** [comment]
Sweet, this works for me now. **Thank you, Adam!**

**Comment by adamjs** [comment]
Awesome! I'll close this issue.
