### ISSUE TITLE
Cannot load external font

### ISSUE THREAD

**Issue by cfadamp** [ultralight-ux/ultralight#55]
**Summarize the Issue**
I could not use my custom font, loaded from file system.

**Steps to Reproduce**
Run the following sample HTML code.

```
<html>
<style> 
@font-face {
    font-family: myFont;
    src: url(C:\\test\\comic.ttf);
}
</style>
	<body>
		<div style="background-color: rgb(0, 0, 0); width: 2112px; height: 1088px;">
			<div style="height: 1016px; width: 1984px; top: 36px; left: 64px;">
				<span style="background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 1); font-family: myFont; font-size: 57.3px;">Sample Text</span>
			</div>
		</div>
	</body>
</html>
```

**Platform Info:**
 - OS: Tried only on Windows.
 - SDK Version 0.9

**Comment by adamjs** [comment]
Hello!

First, there is a small mistake in your URL-- local file URLs should begin with `file:///`. So proper syntax would be: `file:///C:/test/comic.ttf`

Second, all `file:///` URLs are expected to be handled by the user via the `FileSystem` API please see the documentation:  https://github.com/ultralight-ux/ultralight#filesystem

I may add a default FileSystem for each platform in the future (I have neglected to do so because default filesystem access is a bit of a security risk).

Hope this clears up any confusion.
