### ISSUE TITLE
Add support for <select> dropdowns and other native chrome.

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#70]
Native dropdowns currently crash, should expose these for handling by user in a modal callback.

Also other native chrome is not rendering correctly yet (radio buttons / checkboxes), should add a default CSS theme override for these elements.

**Comment by renaudfv** [comment]
What is the status on this?
I'm having trouble rendering select and radio buttons.
Also, does normal form item behaviour have to be taken for granted? Eg. clicking on a text input allows you to edit it, or do we have to implement it?

**Comment by m4heshd** [comment]
I learned this when my project was almost done. Can't finish it without the the `<select>` functionality. So unfortunate. 😔

**Comment by adamjs** [comment]
@m4heshd Native support for `<select>` tag is coming in the upcoming 1.2 branch but you should be able to use any JS replacement to draw/theme these elements.

Here's an example of using the `Selectr` script (plain JS/CSS) to replace all `<select>` elements on a page with themeable CSS widgets: 

https://gist.github.com/adamjs/6e227ca4adc620742b3a3dab27bc38d8

<img width="453" alt="select_example" src="https://user-images.githubusercontent.com/3643751/71770292-8c5aa180-2ef0-11ea-9d66-70d9d8968033.png">

**Comment by m4heshd** [comment]
Hi @adamjs,
Thank you so much for the suggestion. I actually tried a few JS/CSS select elements. But decided to give up because they had some weird rendering issues in the Ultralight window. Same happens with your version. BTW yours look way more cleaner than the other ones I've tried. Take a look at this. It seems to be focusing every single sub element.

![image](https://user-images.githubusercontent.com/6711514/71776249-423af400-2fb4-11ea-84fc-1bd05e0baaee.png)

**Comment by adamjs** [comment]
I think something funky is going on with focus ring painting in that example-- I'll throw it up in a debugger tomorrow and try to fix.

**Comment by m4heshd** [comment]
Please do. Thanks. Also there's this issue. #228.

**Comment by adamjs** [comment]
The focus ring issue should now be fixed in latest trunk.

**Comment by m4heshd** [comment]
Thank you. It works on the x64 version now. Somehow i have this weird permission issue with the AppCore.dll from the x86 build. Can't do anything with that file. Build process also fails at the copying step because of this permission issue. All the x86 builds have this issue.

![image](https://user-images.githubusercontent.com/6711514/71785644-f033b600-3027-11ea-95dd-32dc1f78fc29.png)

**Comment by adamjs** [comment]
@m4heshd You're using the CMake script from the quick-start repo to pull down latest deps? Try deleting your `build` folder manually and rebuild (may need to do it as Administrator), Windows may have locked that file.

**Comment by m4heshd** [comment]
Tried it. Doesn't work with elevated privileges either. Tried manual download, CLI, Winrar everything. x64 build works with no issue. I'm thinking this might be a UAC issue but why for that one specific file?

**Comment by adamjs** [comment]
Support for dropdowns, progress bars, and range sliders is now available in current trunk.
