### ISSUE TITLE
Minimise processing on Main Thread

### ISSUE THREAD

**Issue by Rjvs** [ultralight-ux/Ultralight#95]
**Is your feature request related to a problem? Please describe.**
Allowing JavascriptCore to run on main makes the main thread performance unpredictable.

**Describe the solution you'd like**
Run all of UL on a separate thread.

**Describe alternatives you've considered**
@adamjs says:
> I believe that WebCore/JavaScriptCore assume they have exclusive control over main thread, maybe we can at least redefine which thread is “main”

**Additional context**
This was discussed in [Slack](https://ultralight-ux.slack.com/archives/CC492VBLL/p1553271335773000).

**Comment by adamjs** [comment]
Some updates on this, WebCore/JavaScriptCore actually seems to happily run on a child thread as long as the Renderer and Views are all created on that same thread (it just defines the "main thread" as whatever thread it was initialized on).

The main issue now is we use GLFW for the default, offscreen GL driver and, on macOS at least, it cannot create a GL context on a child thread (it uses NSApplication to run the event loop and in recent versions of macOS, NSApplication must be created on the process's main thread). 

```
2019-03-25 22:56:48.489 Tutorial1[10019:1212519] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff53dfc2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7af9dc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff53e02072 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff55f2b340 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x00007fff55eb9f44 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff5130696e -[NSApplication run] + 997
	6   libUltralightCore.dylib             0x000000010bd1c5f4 initializeAppKit + 436
	7   libUltralightCore.dylib             0x000000010bd1c2ad _glfwPlatformCreateWindow + 29
	8   libUltralightCore.dylib             0x000000010bd13175 glfwCreateWindow + 1077
```

This puts us in a quandary since it means we can't do any hardware-accelerated rendering on a child thread in macOS (Metal also needs NSApplication loop AFAIK).

There's some possible (though inelegant) solutions such as offering an API method like `Platform::UpdateMainThread()` that users using Ultralight from a child-thread must call from their actual main loop so we can perform the actual GLFW initialization on the main thread then switch the OpenGL context to the child thread afterwards.

**Comment by p-groarke** [comment]
Shouldn't your cpu processing stage be seperated from your rendering stage? Meaning, you can run javascript eval on a spawned thread, and later move data to the render thread. Unless you use vulkan/dx12, you *really* don't want to run rendering on a seperate thread, even if you could.

**Comment by Rjvs** [comment]
It might be inelegant but seems like a reasonable stopgap until you can isolate JavaScriptCore from main.  Running anything more than trivial JS on the main thread during gameplay is a real problem.  To me, the appeal of UL is the concept of using web development techniques to do the UI and if that can't include standard JS without threatening frame rate stability, it really limits the usefulness.

**Comment by adamjs** [comment]
The latest build (1.3.0) now supports creating the Renderer on a child thread on all platforms (all further API calls must be made on that same thread). All rasterization can also be performed on non-main threads if the CPU renderer is used (rewritten recently to be faster and more parallel).
